PROTON-2126 Fix Appveyor CI build
Previously, the build would fail when installing setuptools and tox:

```
pip install --user setuptools tox
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pip.exe\__main__.py", line 9, in <module>
TypeError: 'module' object is not callable
Command exited with code 1
```

* Use pip systemwide, not with --user flag
* Use explicit Appveyor image versions in build matrix
* Install VC 9.0, because Python 2.7 needs it

https://www.appveyor.com/docs/windows-images-software/

https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_9.0_standalone:_Visual_C.2B-.2B-_Compiler_for_Python_2.7_.28x86.2C_x64.29

* Don't try detecting sasl on Windows, because MSBuild would fail the py wheel build
* Build also with Python 3.7 x64 to check that is possible
* Fix bad indent in setup.py.in
* Use os.makedirs in setup.py.in, to avoid failue:

```
Error [WinError 3]
	The system cannot find the path specified: 'build\\temp.win-amd64-3.7\\Release\\srcs'
	py_pkg_wheel
	C:\Users\Administrator\qpid-proton\build\python\CUSTOMBUILD	1
```

* Install wheel with pip