PROTON-xxxx: remove unused for cycle counter variable
Some for loops just silently scream to be let out as while

```
[ 83%] Building CXX object cpp/examples/CMakeFiles/tracing_server.dir/tracing_server.cpp.o
/home/jdanek/repos/qpid/qpid-proton/cpp/examples/flow_control.cpp:65:18: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]
        for (int i = sequence; available && s.credit() > 0; i++) {
                 ^
1 error generated.
```