NO-JIRA: Fix break in Javascript bindings build
Attempting to build Proton with Emscripten on the path fails with the following
message:
/home/prestona/git/qpid-proton/examples/c/messenger/recv-async.c:26:10: fatal
error: 'pncompat/misc_funcs.inc' file not found
#include "pncompat/misc_funcs.inc"
         ^
1 error generated.

This appears to have been introduced by commit
84e416e389fe74ec7a1cab9252af2342fc95b83f