PROTON-1035: ConnectionClosed handler uses proper fields for signaling event. Before this patch:   AttributeError: 'ConnectionClosed' object has no attribute 'url' After this patch:   ConnectionClosed: Connection 0.0.0.0:21002 closed due to:   Condition('amqp:resource-limit-exceeded', 'connection disallowed by local policy')